{"status": "broken", "name": "check if addition is successfully completed", "labels": [{"name": "tag", "value": "calculator"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Addition of two number"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1554048833398, "historyId": "16307cdd74a0828af7fad1b55b4c30d4", "start": 1554048831631, "steps": [{"status": "broken", "start": 1554048831649, "stop": 1554048833387, "name": "Given App is launched", "statusDetails": {"message": "WebDriverException: Message: No browserName or app specified in session request. Please check our platforms configurator (https://wiki.saucelabs.com/display/DOCS/Platform+Configurator): {'deviceName': 'device', 'platformName': 'Android', 'appActivity': 'com.android.calculator2.Calculator', 'appPackage': 'com.android.calculator2'}\n\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\Calculation_Steps.py\", line 22, in app_is_launched\n    self.driver = webdriver.Remote('http://'+'Arch2019'+':'+'56b055dc-5081-4163-a14c-0fd3e921950f'+'@ondemand.saucelabs.com:80/wd/hub', desired_caps)\n  File \"c:\\python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 36, in __init__\n    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 208, in check_response\n    raise exception_class(value)\n"}}, {"status": "skipped", "start": 1554048833398, "stop": 1554048833398, "name": "When user adds number"}, {"status": "skipped", "start": 1554048833398, "stop": 1554048833398, "name": "Then output should be displayed"}, {"status": "skipped", "start": 1554048833398, "stop": 1554048833398, "name": "And close app"}], "statusDetails": {"message": "WebDriverException: Message: No browserName or app specified in session request. Please check our platforms configurator (https://wiki.saucelabs.com/display/DOCS/Platform+Configurator): {'deviceName': 'device', 'platformName': 'Android', 'appActivity': 'com.android.calculator2.Calculator', 'appPackage': 'com.android.calculator2'}\n\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\Calculation_Steps.py\", line 22, in app_is_launched\n    self.driver = webdriver.Remote('http://'+'Arch2019'+':'+'56b055dc-5081-4163-a14c-0fd3e921950f'+'@ondemand.saucelabs.com:80/wd/hub', desired_caps)\n  File \"c:\\python27\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 36, in __init__\n    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python27\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 208, in check_response\n    raise exception_class(value)\n"}, "uuid": "7fe0ced9-5da7-44ea-9c71-0cb04f0793dc"}